version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.31
    restart: always
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes: 
      - .dbdata:/var/lib/mysql
